/**
 * Story Export Functions
 */

import { v } from "convex/values";
import { action } from "../_generated/server";
import { api } from "../_generated/api";

/**
 * Export story in various formats
 */
export const exportStory = action({
  args: {
    storyId: v.id("ai_stories"),
    format: v.union(v.literal("pdf"), v.literal("email"), v.literal("csv"), v.literal("shareable-link")),
  },
  handler: async (ctx, args): Promise<any> => {
    const user = await ctx.runQuery(api.users.getCurrentUser);
    if (!user) {
      throw new Error("User not found");
    }

    const story = await ctx.runQuery(api.ai_stories.getStoryById, { storyId: args.storyId });

    if (!story || story.userId !== user._id) {
      throw new Error("Story not found or unauthorized");
    }

    // Get business profile for export formatting
    const businessProfile = await ctx.runQuery(api.businessProfiles.getBusinessProfile);

    const periodLabel = `${new Date(story.periodStart).toLocaleDateString()} to ${new Date(story.periodEnd).toLocaleDateString()}`;

    if (args.format === "csv") {
      // CSV export - key metrics as CSV
      const csvRows: string[] = [];
      csvRows.push("Metric,Value");
      Object.entries(story.keyMetrics).forEach(([key, value]) => {
        csvRows.push(`${key},${value}`);
      });
      const csvContent = csvRows.join("\n");

      return {
        format: "csv",
        content: csvContent,
        filename: `${story.title.replace(/\s+/g, "_")}_metrics.csv`,
        mimeType: "text/csv",
      };
    } else if (args.format === "email") {
      // Email format - HTML email template
      const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${story.title}</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #2563eb;">${story.title}</h1>
  <p style="color: #666; font-size: 14px;">${periodLabel}</p>
  <hr style="border: none; border-top: 2px solid #e5e7eb; margin: 20px 0;">
  <div style="white-space: pre-wrap; margin-top: 20px;">${story.narrative}</div>
  ${Object.keys(story.keyMetrics).length > 0 ? `
  <hr style="border: none; border-top: 2px solid #e5e7eb; margin: 20px 0;">
  <h2 style="color: #2563eb; margin-top: 30px;">Key Metrics</h2>
  <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
    ${Object.entries(story.keyMetrics).map(([key, value]) => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: bold;">${key.replace(/([A-Z])/g, " $1").trim()}</td>
      <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${typeof value === "number" ? value.toLocaleString("en-US", { style: "currency", currency: "USD" }) : String(value)}</td>
    </tr>
    `).join("")}
  </table>
  ` : ""}
  ${story.userNotes ? `
  <hr style="border: none; border-top: 2px solid #e5e7eb; margin: 20px 0;">
  <h2 style="color: #2563eb; margin-top: 30px;">Notes</h2>
  <div style="white-space: pre-wrap; background: #f9fafb; padding: 15px; border-radius: 5px; margin-top: 10px;">${story.userNotes}</div>
  ` : ""}
  <hr style="border: none; border-top: 2px solid #e5e7eb; margin: 20px 0;">
  <p style="color: #666; font-size: 12px; text-align: center; margin-top: 30px;">
    Generated by EZ Financial AI Stories
  </p>
</body>
</html>
      `.trim();

      return {
        format: "email",
        content: emailHtml,
        subject: story.title,
        mimeType: "text/html",
      };
    } else if (args.format === "shareable-link") {
      // Shareable link - generate a unique token (simplified for now)
      // TODO: Implement proper shareable link generation with password protection
      const token = `story_${story._id}_${Date.now()}`;
      const shareableUrl = `${process.env.NEXT_PUBLIC_APP_URL || "https://ezfinancial.app"}/stories/share/${token}`;

      return {
        format: "shareable-link",
        url: shareableUrl,
        token,
        expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000, // 30 days
        message: "Shareable link generated. Full implementation with password protection coming soon.",
      };
    } else {
      // PDF format - return structured data for PDF generation
      // TODO: Implement actual PDF generation using a library like @react-pdf/renderer
      return {
        format: "pdf",
        data: {
          title: story.title,
          period: periodLabel,
          storyType: story.storyType,
          periodType: story.periodType,
          narrative: story.narrative,
          summary: story.summary,
          keyMetrics: story.keyMetrics,
          userNotes: story.userNotes,
          businessName: businessProfile?.legalBusinessName || businessProfile?.dbaTradeName || "Your Business",
          generatedAt: new Date(story.updatedAt).toLocaleDateString(),
        },
        message: "PDF export data prepared. Full PDF generation coming soon.",
      };
    }
  },
});

